# Generated by fusen: do not edit by hand

#' Deduplicate Data
#' 
#' Description
#' 
#' @param .score Dataframe generated by scores_data()
#' @param .source 
#' The Source Dataframe. 
#' Must contain a unique column id and the columns you want to match on
#' @param .target 
#' The Target Dataframe. 
#' Must contain a unique column id and the columns you want to match on
#' @param .col score column generated by scores_data()
#'
#' @return A dataframe
#' 
#' @export
#' @examples
#' tab_source <- table_source[1:100, ]
#' tab_target <- table_target[1:999, ]
#' tab_match <- match_data(
#'   .source = table_source[1:100, ],
#'   .target = table_target[1:999, ],
#'   .cols = c("name", "iso3", "city"),
#'   .min_sim = .2,
#'   .max_match = 10,
#'   .method = "osa", 
#'   .progress = TRUE
#' )
#' tab_score <- scores_data(tab_match)
#' dedup_data(tab_score, tab_source, tab_target, "score_mean")
dedup_data <- function(.score, .source, .target, .col) {
  id_s <- id_t <- name_s <- name_t <- NULL
  
  col_s_ <- colnames(.source)
  col_t_ <- colnames(.target)
  col_e_ <- col_s_[col_s_ %in% col_t_]
  col_e_ <- col_e_[!col_e_ == "id"]
  col_e_ <- unlist(purrr::map2(paste0(col_e_, "_s"), paste0(col_e_, "_t"), c))
  
  tab_ <- .score %>%
    dplyr::select(id_s, id_t, !!dplyr::sym(.col)) %>%
    dplyr::arrange(dplyr::desc(!!dplyr::sym(.col))) %>%
    dplyr::filter(!duplicated(id_t)) %>%
    dplyr::distinct(id_s, .keep_all = TRUE) %>%
    dplyr::full_join(.source, c("id_s" = "id"), FALSE, suffix = c("_s", "_t")) %>%
    dplyr::left_join(.target, c("id_t" = "id"), FALSE, suffix = c("_s", "_t"))
  
  tab_ <- tab_[, c("id_s", "id_t", .col, col_e_)]
  colnames(tab_) <- c("id_s", "id_t", "score", col_e_)
  return(tab_)
}
