# Generated by fusen: do not edit by hand

#' Title
#' 
#' Description
#' 
#' @param .data A dataframe
#' @param .col The column with firm names
#' @param .legal_forms A dataframe with legal forms
#' @param .workers NUmber of workers for parallelisation
#'
#' @return A dataframe
#' 
#' @importFrom rlang :=
#' 
#' @export
#' @examples
#' extract_legal_form(table_source[1:100, ], "name", .workers = 1)
extract_legal_form <- function(.data, .col, .legal_forms = data.frame(), .workers = future::availableCores()) {
  tmp <- legal_form_orig <- legal_form_stand <- legal_form <- name <- NULL
  
  if (nrow(.legal_forms) == 0) {
    tab_lf_ <- get("legal_form_all")
  } else {
    tab_lf_ <- .legal_forms
  }

  tab_ <- standardize_data(.data, .col)
  lf_ <- unique(tab_lf_[["legal_form_orig"]])
  nm_ <- tab_[[.col]]

  f_ <- carrier::crate(function(.lf, .nm) which(endsWith(.nm, paste0(" ", .lf))))
  future::plan("multisession", workers = 6)
  lf_ext_ <- furrr::future_map(
    .x = purrr::set_names(lf_, lf_),
    .f = ~ f_(.x, nm_),
    .options = furrr::furrr_options(seed = TRUE)
  )
  future::plan("default")
  lf_ext_ <- lf_ext_ %>%
    purrr::compact() %>%
    tibble::enframe(name = "legal_form_orig", value = "tmp") %>%
    tidyr::unnest(tmp) %>%
    dplyr::arrange(dplyr::desc(nchar(legal_form_orig))) %>%
    dplyr::distinct(tmp, .keep_all = TRUE)

  tab_ %>%
    dplyr::mutate(tmp = dplyr::row_number()) %>%
    dplyr::left_join(lf_ext_, by = "tmp") %>%
    dplyr::left_join(tab_lf_, by = c("iso3", "legal_form_orig")) %>%
    dplyr::rename(legal_form = legal_form_stand) %>%
    dplyr::relocate(legal_form, .after = !!dplyr::sym(.col)) %>%
    dplyr::mutate(
      !!dplyr::sym(paste0(.col, "_adj")) := trimws(
        stringi::stri_replace_last_fixed(name, legal_form_orig, "")
      ),
      .after = !!dplyr::sym(.col)
    ) %>%
    dplyr::mutate(
      !!dplyr::sym(paste0(.col, "_adj")) := dplyr::if_else(
        condition = is.na(!!dplyr::sym(paste0(.col, "_adj"))),
        true = !!dplyr::sym(.col), 
        false = !!dplyr::sym(paste0(.col, "_adj"))
        )) %>%
    dplyr::mutate(
      !!dplyr::sym(paste0(.col, "_std")) := dplyr::if_else(
        condition = !is.na(legal_form),
        true = paste(!!dplyr::sym(paste0(.col, "_adj")), legal_form),
        false = !!dplyr::sym(paste0(.col, "_adj"))
      ),
      .after = !!dplyr::sym(paste0(.col, "_adj"))
    ) %>%
    dplyr::select(-legal_form_orig, -tmp)
  
  
}
