# Generated by fusen: do not edit by hand

#' Title
#' 
#' Description
#' 
#' @param .data A dataframe
#' @param ... Any number of columns to check
#'
#' @return A dataframe
#' 
#' @export
#' @examples
#' # filter_duplicates()
filter_duplicates <- function(.data, ...) {
  tmp_ <- NULL
  vars_ <- dplyr::enquos(...)
  tibble::as_tibble(.data) %>%
    dplyr::mutate(tmp_ = paste0(!!!vars_)) %>%
    dplyr::filter(duplicated(tmp_) |duplicated(tmp_, fromLast = TRUE)) %>%
    dplyr::select(-tmp_) %>%
    dplyr::arrange(!!!vars_)
}
