# Generated by fusen: do not edit by hand

#' Get Weights
#' 
#' Description
#' 
#' @param .data A Dataframe
#' @param .cols columns
#'
#' @return A numeric vector
#' 
#' @export
#' @examples
#' get_weights(table_source, c("name", "city", "address"))
get_weights <- function(.data, .cols) {
  . <- NULL
  purrr::map_dbl(
    .x = stats::setNames(.cols, .cols), 
    .f = ~ mean(uniqueness_vec(.data[[.x]]), na.rm = TRUE)
    ) %>% `/`(sum(., na.rm = TRUE))
}
