# Generated by fusen: do not edit by hand

#' Perform LeftJoin on Data
#' 
#' Description
#' 
#' @param .source 
#' The Source Dataframe. 
#' Must contain a unique column id and the columns you want to match on
#' @param .target 
#' The Target Dataframe. 
#' Must contain a unique column id and the columns you want to match on
#' @param .cols 
#' The column names to match as character vector
#' @param .join
#' Columns to match on
#' @param .method 
#' One of "osa", "lv", "dl", "hamming", "lcs", "qgram", "cosine", "jaccard", "jw", "soundex"
#' @return A Dataframe
#' 
#' @export
#' @examples
#' join_data(
#'   .source = table_source,
#'   .target = table_target,
#'   .cols = c("name", "iso3", "city", "address"),
#'   .join = c("name", "iso3"),
#'   .method = "osa"
#' )
join_data <- function(.source, .target, .cols, .join, .method = "osa") {
  id_s <- id_t <- NULL
  .source <- tibble::as_tibble(.source)
  .target <- tibble::as_tibble(.target)
  
  check_id(.source, .target)
  
  s_ <- .source[, c("id", .join)]
  t_ <- .target[, c("id", .join)]
  non_ <- .cols[!.cols %in% .join]

  tab_ <- dplyr::inner_join(s_, t_, by = .join, suffix = c("_s", "_t")) %>%
    dplyr::mutate(
      dplyr::across(!dplyr::matches("^id_s$|^id_t$"), ~1)
    ) %>%
    dplyr::select(id_s, id_t, dplyr::everything()) %>%
    `colnames<-`(c("id_s", "id_t", paste0("sim_", .join)))

  s_ <- dplyr::left_join(tab_, .source[, c("id", non_)], by = c("id_s" = "id"))
  t_ <- dplyr::left_join(tab_, .target[, c("id", non_)], by = c("id_t" = "id"))

  for (i in seq_len(length(non_))) {
    tab_[[paste0("sim_", non_[i])]] <- stringdist::stringsim(s_[[non_[i]]], t_[[non_[i]]], .method)
  }
  
  return(tab_)
}
