# Generated by fusen: do not edit by hand

#' Match a on a single column
#' 
#' Description
#' 
#' @param .source 
#' The Source Dataframe. 
#' Must contain a unique column id and the columns you want to match on
#' @param .target 
#' The Target Dataframe. 
#' Must contain a unique column id and the columns you want to match on
#' @param .col 
#' The column name to match as a string
#' @param .max_match 
#' Maximum number of matches to return (Default = 10)
#' @param .min_sim 
#' Minimum Similarity as defined by the chosen method
#' @param .method 
#' One of "osa", "lv", "dl", "hamming", "lcs", "qgram", "cosine", "jaccard", "jw", "soundex"
#' See stringdist package
#'
#' @return A Dataframe
#' @noRd
#' @examples
#' match_col(
#'   .source = table_source[1:100, ],
#'   .target = table_target[1:999, ],
#'   .col = "name",
#'   .max_match = 10,
#'   .min_sim = .2,
#'   .method = "osa"
#' )
match_col <- function(.source, .target, .col, .max_match = 10, .min_sim = .2, .method = "osa") {
  V1 <- value <- id <- name <- id_t <- sim <- NULL
  .source <- tibble::as_tibble(.source)
  .target <- tibble::as_tibble(.target)
  
  
  check_id(.source, .target)
  
  method_ <- match.arg(
    arg = .method,
    choices = c(
      "osa", "lv", "dl", "hamming", "lcs", "qgram", "cosine",
      "jaccard", "jw", "soundex"
    )
  )
  
  tab_ <- stringdist::stringsimmatrix(
    a = .source[[.col]],
    b = .target[[.col]],
    method = method_
  ) %>%
    tibble::as_tibble() %>%
    dplyr::mutate(id = dplyr::row_number(), .before = V1) %>%
    tidyr::pivot_longer(!dplyr::matches("id")) %>%
    dplyr::filter(value >= .min_sim) %>%
    dplyr::group_by(id) %>%
    dplyr::slice_max(order_by = value, n = .max_match) %>%
    dplyr::ungroup() %>%
    dplyr::rename(id_s = id, id_t = name) %>%
    dplyr::mutate(id_t = as.integer(gsub("V", "", id_t, fixed = TRUE))) %>%
    suppressWarnings()
  tab_[["id_s"]] <- .source[["id"]][tab_[["id_s"]]]
  tab_[["id_t"]] <- .target[["id"]][tab_[["id_t"]]]
  colnames(tab_) <- c("id_s", "id_t", paste0("sim_", .col))
  return(tab_)
}
