# Generated by fusen: do not edit by hand

#' Match Data
#' 
#' Description
#' 
#' @param .source 
#' The Source Dataframe. 
#' Must contain a unique column id and the columns you want to match on
#' @param .target 
#' The Target Dataframe. 
#' Must contain a unique column id and the columns you want to match on
#' @param .cols 
#' The column names to match as character vector
#' @param .join
#' Columns to match on
#' @param .max_match 
#' Maximum number of matches to return (Default = 10)
#' @param .min_sim 
#' Minimum Similarity as defined by the chosen method
#' @param .method 
#' One of "osa", "lv", "dl", "hamming", "lcs", "qgram", "cosine", "jaccard", "jw", "soundex"
#' @param .must_match Columns that must be matched perfectly
#' @param .progress Should a progress bar be shown?
#' See stringdist package
#' @param .chunk Chunk your data
#'
#' @return A dataframe
#' 
#' @export
#' @examples
#' tab_source <- table_source[1:100, ]
#' tab_target <- table_target[1:999, ]
#' cols <- c("name", "iso3", "city", "address")
#' must <- "iso3"
#' match_data(
#'   .source = tab_source,
#'   .target = tab_target,
#'   .cols = cols,
#'   .must_match = must,
#' )
match_data <- function(.source, .target, .cols, .join = NULL, .must_match = NULL, .max_match = 10,
                       .min_sim = .2, .method = "osa", .chunk = 1, .progress = TRUE) {
  id <- NULL
  .source <- tibble::as_tibble(.source)
  .target <- tibble::as_tibble(.target)
  
  
  check_id(.source, .target)
  
  if (!is.null(.join)) {
    tab0_ <- join_data(.source, .target, .cols, .join)
    s_ <- dplyr::filter(.source, !id %in% tab0_$id_s)
    t_ <- dplyr::filter(.target, !id %in% tab0_$id_t)
  } else {
    tab0_ <- tibble::tibble(id_s = "", .rows = 0)
    s_ <- .source
    t_ <- .target
  }


  if (.chunk > 1) {
    ls_ <- split(
      x = s_,
      f = rep(1:.chunk, each = ceiling(nrow(s_) / .chunk))[1:nrow(s_)]
    )
  } else {
    ls_ <- list("1" = s_)
  }


  tab1_ <- purrr::imap_dfr(
    .x = ls_,
    .f = ~ {
      if (.progress) cat("\rITERATION", .y)
      help_match_data(
        .source = .x,
        .target = t_,
        .cols = .cols,
        .must_match = .must_match,
        .max_match = .max_match,
        .min_sim = .min_sim,
        .method = .method,
        .progress = .progress
      )
    }
  )

  out_ <- dplyr::bind_rows(tab0_, tab1_)
  out_ <- out_[, c("id_s", "id_t", paste0("sim_", .cols))]
  
}
