# Generated by fusen: do not edit by hand

#' Score Data
#' 
#' Description
#' 
#' @param .matches Dataframe produced by match_data()
#' @param .source 
#' The Source Dataframe. 
#' Must contain a unique column id and the columns you want to match on
#' @param .target 
#' The Target Dataframe. 
#' Must contain a unique column id and the columns you want to match on
#' @param .must_match Columns that must be matched perfectly
#' @param .w_unique Weights calucalted by get_weights()
#' @param .w_custom Custom weights
#'
#' @return A dataframe
#' 
#' @export
#' @examples
#' tab_source <- table_source[1:100, ]
#' tab_target <- table_target[1:999, ]
#' cols <- c("name", "iso3", "city", "address")
#' must <- "iso3"
#' tab_match <- match_data(
#'   .source = tab_source,
#'   .target = tab_target,
#'   .cols = cols,
#'   .must_match = must,
#' )
#' scores_data(
#'   .matches = tab_match,
#'   .source = tab_source,
#'   .target = tab_target,
#'   .must_match = must
#' )
scores_data <- function(.matches, .source, .target, .must_match = NULL, 
                        .w_unique = NULL, .w_custom = NULL) {
  id_s <- id_t <- . <- NULL
  
  .matches <- tibble::as_tibble(.matches)
  .source  <- tibble::as_tibble(.source)
  .target  <- tibble::as_tibble(.target)
  
  cols_ <- colnames(.matches)
  cols_ <- gsub("sim_", "", cols_[grepl("^sim_", cols_)])
  cols_ <- cols_[!cols_ %in% .must_match]
  
  if (!is.null(.w_unique)) {
    help_check_weights(.w_unique, cols_)
    wu_ <- .w_unique
  } else {
    wu_ <- (get_weights(.source, cols_) + get_weights(.target, cols_)) / 2
  }
  
  if (!is.null(.w_custom)) {
    help_check_weights(.w_custom, cols_)
    wc_ <- .w_custom[order(match(names(.w_custom), cols_))]
    wc_ <- wc_ / sum(wc_)
  } else {
    wc_ <- rep(NA_real_, length(cols_))
  }

  mat_ <- as.matrix(.matches[, paste0("sim_", cols_)])
  
  .matches %>%
    dplyr::select(id_s, id_t, dplyr::starts_with("sim_")) %>%
    dplyr::mutate(
      mean_simple = rowMeans(mat_, na.rm = TRUE),
      mean_weight = rowSums(mat_ * wu_, na.rm = TRUE),
      mean_custom = rowSums(mat_ * wc_, na.rm = TRUE)
    )
}
