# Generated by fusen: do not edit by hand

#' Score Data
#' 
#' Description
#' 
#' @param .data A dataframe
#' @param .weights Custom weights
#' @param .training A training dataset (not implemented yet)
#'
#' @return A dataframe
#' 
#' @export
#' @examples
#' tab_match <- match_data(
#'   .source = table_source[1:100, ],
#'   .target = table_target[1:999, ],
#'   .cols = c("name", "iso3", "city"),
#'   .min_sim = .2,
#'   .max_match = 10,
#'   .method = "osa", 
#'   .progress = TRUE
#' )
#' tab_score <- scores_data(tab_match)
scores_data <- function(.data, .weights = NULL, .training = NULL) {
  id_s <- id_t <- NULL
  tab_ <- tibble::as_tibble(.data)
  cols_ <- colnames(tab_)
  cols_ <- cols_[grepl("^sim_|^uni_", cols_)]
  mat_ <- as.matrix(tab_[, cols_])
  
  if (!is.null(.weights)) {
    if (length(.weights) != length(cols_)) {
      stop("Weights must have the same length as columns to weigh", call. = FALSE)
    }
    
    weights_ <- .weights / sum(.weights)
    
    mat_ <- mat_ * weights_
    tab_ %>%
      dplyr::select(id_s, id_t) %>%
      dplyr::mutate(
        score_mean = rowMeans(mat_, na.rm = TRUE),
        score_square = rowMeans(mat_^2, na.rm = TRUE)
      )
  } else {
    tab_ %>%
      dplyr::select(id_s, id_t) %>%
      dplyr::mutate(
        score_mean = rowMeans(mat_, na.rm = TRUE),
        score_square = rowMeans(mat_^2, na.rm = TRUE)
      )
  }
  
  

  
}
