# Generated by fusen: do not edit by hand

#' Title
#' 
#' Description
#' 
#' @param .data A dataframe
#' @param .cols Columns to standardize
#' @param .fun Function for standardization, if NULL standardize_str() is used
#'
#' @return A dataframe
#' 
#' @export
#' @examples
#' standardize_data(table_source, c("name", "iso3", "city", "address"))
standardize_data <- function(.data, .cols, .fun = NULL) {
  tab_ <- .data
  if (is.null(.fun)) {
    f_ <- standardize_str
  } else {
    f_ <- .fun
  }
  
  for (i in .cols) {
    tab_[[i]] <- f_(tab_[[i]])
  }
  return(tab_)
}
