# Generated by fusen: do not edit by hand

#' Standardize Strings
#' 
#' Description
#' 
#' @param .str A string
#' @param .op Operations to perform
#'
#' @return A string
#' 
#' @export
#' @examples
#' standardize_str(c("jkldsa   jkdhas   Ã¤Ã¤Ã¤  Â§$ ## #'''"))
standardize_str <- function(.str, .op = c("space", "punct", "case", "utf8")) {
  str_ <- .str
  
  if ("punct" %in% .op) {
    str_ <- trimws(stringi::stri_replace_all_regex(str_, "\\W", " "))
    str_ <- trimws(stringi::stri_replace_all_regex(str_, "[[:punct:]]", " "))
    
    if (!"space" %in% .op) {
      str_ <- trimws(stringi::stri_replace_all_regex(str_, "([[:blank:]]|[[:space:]])+", " "))
    }
  }
  
  if ("space" %in% .op) {
    str_ <- trimws(stringi::stri_replace_all_regex(str_, "([[:blank:]]|[[:space:]])+", " "))
  }
  
  if ("case" %in% .op) {
    str_ <- toupper(str_)
  }
  
  if ("utf8" %in% .op) {
    str_ <- stringi::stri_enc_toutf8(str_)
  }
  
  return(str_)
  
}
