# Generated by fusen: do not edit by hand

#' Title
#' 
#' Description
#' 
#' @param .data A dataframe
#' @param .cols Columns to standardize
#' @param .op Operations to perform
#'
#' @return A dataframe
#' 
#' @export
#' @examples
#' standardize_data(source, c("name", "iso3", "city", "address"))
standardize_data <- function(.data, .cols, .op = c("space", "punct", "case", "utf8")) {
    
  tab_ <- .data
  for (i in .cols) {
    tab_[[i]] <- standardize_str(tab_[[i]])
  }
  
  return(tab_)
  
}
