# Generated by fusen: do not edit by hand

#' Calculate Uniqueness of Data
#' 
#' Description
#' 
#' @param .data A Dataframe
#' @param .cols Column as character vector
#' @param .type either source or target
#'
#' @return A dataframe
#' 
#' @export
#' @examples
#' uniqueness_data(table_source[1:100, ], c("name", "iso3", "city", "address"), "source")
uniqueness_data <- function(.data, .cols, .type = c("source", "target")) {
  id <- tmp <- NULL
  type_ <- match.arg(.type, c("source", "target"))
  type_ <- substr(type_, 1, 1)
  tab_ <- .data[, c("id", .cols)] %>%
    tidyr::unite(tmp, !dplyr::matches("^id$"))
  tab_[[paste0("uni_", type_)]] <- uniqueness_vec(tab_[["tmp"]])
  tab_ <- dplyr::select(tab_, -tmp)
  colnames(tab_) <- c(paste0("id_", type_), paste0("uni_", type_))
  return(tab_)
}
