# Generated by fusen: do not edit by hand

#' Uniquness/Rarity of a vector 
#' 
#' Description
#' 
#' @param .vec A character vector
#'
#' @return A numeric vector
#' 
#' @noRd
#' @examples
#' uniqueness_vec(table_source[["name"]][1:10])
uniqueness_vec <- function(.vec) {
  l1_ <- stringi::stri_split_fixed(.vec, " ")
  v1_ <- unlist(l1_)
  v2_ <- as.integer(stats::ave(v1_, v1_, FUN = length))
  l2_ <- utils::relist(v2_, l1_)
  v3_ <- purrr::map_int(l2_, ~ sum(.x, na.rm = TRUE))
  
  1 - (v3_ / max(v3_))
}
