# Generated by fusen: do not edit by hand

#' Title
#' 
#' Description
#' 
#' @param .data A Dataframe
#' @param .cols Column as character vector
#' @param .type either source or target
#'
#' @return A dataframe
#' 
#' @export
#' @examples
#' uniqueness_data(source, c("name", "iso3", "city", "address"), "source")
uniqueness_data <- function(.data, .cols, .type = c("source", "target")) {
  id <- NULL
  type_ <- match.arg(.type, c("source", "target"))
  type_ <- substr(type_, 1, 1)
  tab_ <- .data

  for (i in seq_len(length(.cols))) {
    tab_[[paste0("uni_", type_, i)]] <- uniqueness_vec(tab_[[.cols[i]]])
  }
  
  tab_ <- dplyr::select(tab_, id, dplyr::starts_with("uni_"))
  
  if (.type == "source") {
    dplyr::rename(tab_, id_s = id)
  } else {
    dplyr::rename(tab_, id_t = id)
  }
  
}
