# Generated by fusen: do not edit by hand

#' Uniquness/Rarity of a vector 
#' 
#' Description
#' 
#' @param .vec A character vector
#' @param .normalize Normalize between 0 and 1
#'
#' @return A numeric vector
#' 
#' @noRd
#' @examples
#' uniqueness_vec(table_source[["name"]][1:10], TRUE)
uniqueness_vec <- function(.vec, .normalize = FALSE) {
  value <- name <- n <- NULL
  
  l1_ <- stringi::stri_extract_all_regex(.vec, ".")
  mat_ <- tibble::enframe(l1_) %>%
    tidyr::unnest(value) %>%
    dplyr::count(name, value) %>%
    tidyr::pivot_wider(names_from = value, values_from = n, values_fill = 0) %>%
    dplyr::select(-name) %>%
    as.matrix()
  man_ <- Rfast::Dist(mat_, method = "manhattan")
  if (.normalize) {
    man_ <- man_ / max(man_)
  }
  
  rowMeans(man_)
}
